### ISSUE TITLE
CPL File

### ISSUE THREAD

**Issue by nicolocarcagni** [elVucko/Duino_Coin_AVR#2]
Hi, can you add the CPL? I need it for JLCPCB
There's a sample [https://jlcpcb.com//video/JLCSMT_Sample_CPL1.xlsx?_ga=2.19650808.1931900423.1650716192-1476452342.1648375495&_gac=1.16912331.1650716192.CjwKCAjwx46TBhBhEiwArA_DjEUBKml_yAA1PaGkPxgTZW3rSurY9-y1C894mUQ6OZ8IGE_1M7f6yRoCqXoQAvD_BwE](url)

**Comment by elVucko** [comment]
I'm sorry, I was very busy and I didn't get to answer you earlier. I will add a CPL file in the coming days.
